version: "3.9"
services:
  train:
    image: cvat2trainedyolo:latest
    build:
      context: .
      shm_size: "30gb"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    volumes:
      - ./config:/config
      - ./weights:/weights
      - ./config:/input
      - ./dataset:/dataset
      - ./test:/test
    shm_size: "30gb"
    restart: "no"
    stdin_open: true
    tty: true
